export const brands = [
    "Abart", "Acura", "Aixam", "Alfa Romeo", "Aro", "Aston Martin", "Audi", "Austin", "Baic", "Bentley", "BMW",
    "Bugatti", "Buick", "Cadillac", "Chevrolet", "Chrysler", "Citroen", "Comarth", "Dacia", "Daewoo", "Daihatsu",
    "DFSK", "Dodge", "Ferrari", "Fiat", "Fisker", "Ford", "Minibus", "Honda", "Hummer", "Hyundai", "Ineos",
    "Infiniti", "Isuzu", "Jaguar", "Jeep", "KG Mobility", "Kia", "Lada", "Lamborghini", "Lancia", "Land Rover",
    "Lexus", "Ligier", "Lincoln", "Lotus", "Lucid", "Lynk&Co", "Maserati", "Mazda", "McLaren", "Maybach", "Merceds-Benz",
    "MG", "Microlinio", "Mini", "Mitsubishi", "Microcar", "Morgan", "Nissan","Opel","Peugeot","Plymouth","Pontiac",
    "Porsche","Renault","Rolls-Royce","Rover","Saab","Seat","Skoda","Smart","SsangYong","Skywell","Subaru","Suzuki",
    "Tesla","Tata","Tazzari","Toyota","Trabant","Triumph","Vauxhall","Volkswagen","Volvo","Weismann","Alte marci",
    "JAC","SWM","Forthing","XEV"
  ];
export const modelsByBrand = {
    Abart: ["500", "595", "124 Spider"],
    Acura: ["ILX", "MDX", "NSX", "RDX", "RLX", "TLX"],
    Aixam: ["City", "Crossline", "Coupé", "Scouty"],
    "Alfa Romeo": ["Giulia", "Stelvio", "Giulietta", "4C", "Spider"],
    Aro: ["10", "24", "244", "324"],
    "Aston Martin": ["DB11", "DBX", "Vantage", "DBS", "Rapide"],
    Audi: ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "TT", "R8"],
    Austin: ["Mini", "A30", "A40", "Healey"],
    Baic: ["X25", "X35", "BJ40", "Senova D50"],
    Bentley: ["Continental", "Bentayga", "Flying Spur", "Mulsanne"],
    BMW: ["Series 1", "Series 2", "Series 3", "Series 4", "Series 5", "Series 6", "Series 7", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4"],
    Bugatti: ["Chiron", "Veyron", "Divo", "La Voiture Noire"],
    Buick: ["Encore", "Enclave", "Regal", "LaCrosse"],
    Cadillac: ["Escalade", "XT4", "XT5", "CT6", "CTS", "ATS"],
    Chevrolet: ["Camaro", "Corvette", "Impala", "Silverado", "Suburban", "Tahoe", "Trax"],
    Chrysler: ["300", "Pacifica", "Voyager"],
    Citroen: ["C1", "C3", "C4", "C5 Aircross", "Berlingo", "SpaceTourer"],
    Comarth: ["XTamy", "Cross Rider", "S1", "XTamy4"],
    Dacia: ["Duster", "Sandero", "Logan", "Lodgy", "Dokker"],
    Daewoo: ["Matiz", "Nubira", "Lanos", "Leganza"],
    Daihatsu: ["Terios", "Copen", "Sirion", "Materia"],
    DFSK: ["Glory 580", "C31", "C35", "C37"],
    Dodge: ["Challenger", "Charger", "Durango", "Ram"],
    Ferrari: ["488", "Portofino", "Roma", "F8", "812", "SF90"],
    Fiat: ["500", "Panda", "Tipo", "Punto", "Doblo", "500X", "500L"],
    Fisker: ["Karma", "Ocean"],
    Ford: ["Fiesta", "Focus", "Mustang", "Kuga", "Edge", "Explorer", "Ranger", "F-150"],
    Honda: ["Civic", "Accord", "CR-V", "Jazz", "HR-V", "Pilot", "Fit"],
    Hummer: ["H1", "H2", "H3", "EV"],
    Hyundai: ["i10", "i20", "i30", "Elantra", "Tucson", "Santa Fe", "Kona"],
    Ineos: ["Grenadier"],
    Infiniti: ["Q50", "Q60", "QX50", "QX60", "QX80"],
    Isuzu: ["D-Max", "MU-X", "Trooper", "Rodeo"],
    Jaguar: ["XE", "XF", "XJ", "F-Pace", "E-Pace", "F-Type"],
    Jeep: ["Wrangler", "Cherokee", "Grand Cherokee", "Renegade", "Compass", "Gladiator"],
    "KG Mobility": ["Tivoli", "Rexton", "Korando", "Musso"],
    Kia: ["Rio", "Ceed", "Sportage", "Sorento", "Stonic", "Stinger", "Niro"],
    Lada: ["Niva", "Granta", "Vesta", "XRay"],
    Lamborghini: ["Aventador", "Huracan", "Urus"],
    Lancia: ["Ypsilon", "Delta", "Thema"],
    "Land Rover": ["Defender", "Discovery", "Range Rover", "Evoque", "Velar"],
    Lexus: ["IS", "ES", "GS", "LS", "RX", "NX", "UX"],
    Ligier: ["JS50", "JS60", "Pulse 3"],
    Lincoln: ["Navigator", "Aviator", "Corsair", "Continental"],
    Lotus: ["Elise", "Exige", "Evora"],
    Lucid: ["Air", "Gravity"],
    "Lynk&Co": ["01", "02", "03", "05", "06", "09"],
    Maserati: ["Ghibli", "Quattroporte", "Levante", "GranTurismo"],
    Mazda: ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-5", "MX-5"],
    McLaren: ["570S", "720S", "GT", "P1"],
    Maybach: ["S-className", "GLS"],
    "Merceds-Benz": ["A-className", "C-className", "E-className", "S-className", "GLA", "GLC", "GLE", "GLS", "G-className", "Vito", "Sprinter"],
    MG: ["ZS", "HS", "5", "MG4"],
    Microlinio: ["Lite", "Pioneer", "Ranger"],
    Mini: ["Cooper", "Clubman", "Countryman"],
    Mitsubishi: ["Mirage", "Outlander", "ASX", "L200"],
    Microcar: ["M.Go", "M8", "Dué"],
    Morgan: ["Plus Four", "Plus Six"],
    Nissan: ["Micra", "Juke", "Qashqai", "X-Trail", "Leaf", "Navara"],
    Opel: ["Corsa", "Astra", "Insignia", "Mokka", "Crossland", "Grandland"],
    Peugeot: ["208", "308", "508", "2008", "3008", "5008"],
    Plymouth: ["Barracuda", "Fury", "Road Runner"],
    Pontiac: ["Firebird", "GTO", "Bonneville"],
    Porsche: ["911", "Cayenne", "Panamera", "Taycan", "Macan", "Boxster", "Cayman"],
    Renault: ["Clio", "Megane", "Captur", "Kadjar", "Koleos", "Talisman"],
    "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Cullinan"],
    Rover: ["200", "400", "600", "800"],
    Saab: ["9-3", "9-5", "900", "9000"],
    Seat: ["Ibiza", "Leon", "Ateca", "Arona", "Tarraco"],
    Skoda: ["Fabia", "Octavia", "Superb", "Kodiaq", "Karoq"],
    Smart: ["ForTwo", "ForFour"],
    SsangYong: ["Tivoli", "Korando", "Rexton", "Musso"],
    Skywell: ["ET5", "ET6"],
    Subaru: ["Impreza", "Legacy", "Outback", "Forester", "XV", "WRX"],
    Suzuki: ["Swift", "Vitara", "S-Cross", "Jimny"],
    Tesla: ["Model S", "Model 3", "Model X", "Model Y"],
    Tata: ["Nexon", "Safari", "Harrier"],
    Tazzari: ["Zero", "Em2"],
    Toyota: ["Yaris", "Corolla", "Camry", "RAV4", "Land Cruiser", "Hilux"],
    Trabant: ["601", "P50", "1.1"],
    Triumph: ["Herald", "TR6", "Spitfire"],
    Vauxhall: ["Corsa", "Astra", "Insignia"],
    Volkswagen: ["Golf", "Passat", "Polo", "Tiguan", "Touareg", "T-Roc", "ID.3", "ID.4"],
    Volvo: ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"],
    Weismann: ["MF3", "MF4", "GT"],
    "Alte marci": ["Dacia 1300", "ARO M461", "ARO 244"],
    JAC: ["S2", "S3", "S5"],
    SWM: ["G01", "X3", "X7"],
    Forthing: ["T5 EVO", "Thunder EV"],
    XEV: ["Yoyo"],
};
export const bodies = ["Cabrio", "Sedan", "Coupe", "Pickup", "HatchBack", "Break", "Off-road", "Minibus", "Monovolum", "SUV" ];
export const colors = [
    "Almond", "Alpine White", "Amethyst", "Anthracite", "Aqua", "Arctic White", "Azure", "Beige", "Black", 
      "Black Cherry", "Black Diamond", "Black Pearl", "Black Sapphire", "Blue", "Blue Diamond", "Blue Metallic", 
      "Brilliant Black", "Brilliant Blue", "Bronze", "Brown", "Burgundy", "Candy Apple Red", "Carbon Black", 
      "Cavansite Blue", "Champagne", "Charcoal", "Cobalt Blue", "Copper", "Cream", "Crimson", "Crystal White", 
      "Dark Blue", "Dark Green", "Dark Red", "Daytona Gray", "Deep Black Pearl", "Deep Blue", "Deep Green", 
      "Desert Sand", "Designo Diamond White", "Designo Manufaktur", "Designo Selenite Gray Magno", 
      "Diamond Silver", "Dove Gray", "Electric Blue", "Emerald Green", "Estoril Blue", "Floret Silver", 
      "Forest Green", "Frozen Brilliant White", "Frozen Silver", "Frozen White", "Glacier Blue", "Glacier White", 
      "Gold", "Graphite", "Gray", "Green", "Gunmetal", "Ice Blue", "Ibis White", "Indium Gray", "Iridium Silver", 
      "Ivory", "Jet Black", "Lapis Blue", "Lava Orange", "Lavender", "Le Mans Blue", "Lime Green", 
      "Limestone Gray", "Magenta", "Maroon", "Matte Black", "Melbourne Red", "Midnight Blue", "Mineral White", 
      "Mint Green", "Misano Red", "Moonlight Silver", "Mojave Silver", "Mythos Black", "Nardo Gray", 
      "Navarra Blue", "Navy Blue", "Night Blue", "Ocean Blue", "Olive Green", "Onyx Black", "Orange", 
      "Oryx White Pearl", "Pale Blue", "Pearl White", "Phantom Black", "Pink", "Platinum", "Platinum Gray", 
      "Polar White", "Pure White", "Purple", "Racing Green", "Raven Black", "Red", "Reflex Silver", 
      "Riviera Blue", "Rose Gold", "Ruby Red", "Saffron", "San Marino Blue", "Sand", "Sapphire Black", 
      "Sapphire Blue", "Sepang Blue", "Shadow Black", "Silver", "Sky Blue", "Slate Gray", "Slenite Gray", 
      "Snow White", "Sophisto Gray", "Steel Blue", "Storm Gray", "Sunset Orange", "Super White", "Suzuka Gray", 
      "Tan", "Tango Red", "Tanzanite Blue", "Teal", "Titanium", "Tornado Red", "Turquoise", "Vesuvius Gray", 
      "Viper Green", "White", "Yellow"
  ];
