export const brands = [
    "Abart", "Acura", "Aixam", "Alfa Romeo", "Aro", "Aston Martin", "Audi", "Austin", "Baic", "Bentley", "BMW",
    "Bugatti", "Buick", "Cadillac", "Chevrolet", "Chrysler", "Citroen", "Comarth", "Dacia", "Daewoo", "Daihatsu",
    "DFSK", "Dodge", "Ferrari", "Fiat", "Fisker", "Ford", "Minibus", "Honda", "Hummer", "Hyundai", "Ineos",
    "Infiniti", "Isuzu", "Jaguar", "Jeep", "KG Mobility", "Kia", "Lada", "Lamborghini", "Lancia", "Land Rover",
    "Lexus", "Ligier", "Lincoln", "Lotus", "Lucid", "Lynk&Co", "Maserati", "Mazda", "McLaren", "Maybach", "Merceds-Benz",
    "MG", "Microlinio", "Mini", "Mitsubishi", "Microcar", "Morgan", "Nissan","Opel","Peugeot","Plymouth","Pontiac",
    "Porsche","Renault","Rolls-Royce","Rover","Saab","Seat","Skoda","Smart","SsangYong","Skywell","Subaru","Suzuki",
    "Tesla","Tata","Tazzari","Toyota","Trabant","Triumph","Vauxhall","Volkswagen","Volvo","Weismann","Alte marci",
    "JAC","SWM","Forthing","XEV"
  ];
export const modelsByBrand = {
    Abart: ["500", "595", "124 Spider"],
    Acura: ["ILX", "MDX", "NSX", "RDX", "RLX", "TLX"],
    Aixam: ["City", "Crossline", "Coupé", "Scouty"],
    "Alfa Romeo": ["Giulia", "Stelvio", "Giulietta", "4C", "Spider"],
    Aro: ["10", "24", "244", "324"],
    "Aston Martin": ["DB11", "DBX", "Vantage", "DBS", "Rapide"],
    Audi: ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "TT", "R8"],
    Austin: ["Mini", "A30", "A40", "Healey"],
    Baic: ["X25", "X35", "BJ40", "Senova D50"],
    Bentley: ["Continental", "Bentayga", "Flying Spur", "Mulsanne"],
    BMW: ["Series 1", "Series 2", "Series 3", "Series 4", "Series 5", "Series 6", "Series 7", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4"],
    Bugatti: ["Chiron", "Veyron", "Divo", "La Voiture Noire"],
    Buick: ["Encore", "Enclave", "Regal", "LaCrosse"],
    Cadillac: ["Escalade", "XT4", "XT5", "CT6", "CTS", "ATS"],
    Chevrolet: ["Camaro", "Corvette", "Impala", "Silverado", "Suburban", "Tahoe", "Trax"],
    Chrysler: ["300", "Pacifica", "Voyager"],
    Citroen: ["C1", "C3", "C4", "C5 Aircross", "Berlingo", "SpaceTourer"],
    Comarth: ["XTamy", "Cross Rider", "S1", "XTamy4"],
    Dacia: ["Duster", "Sandero", "Logan", "Lodgy", "Dokker"],
    Daewoo: ["Matiz", "Nubira", "Lanos", "Leganza"],
    Daihatsu: ["Terios", "Copen", "Sirion", "Materia"],
    DFSK: ["Glory 580", "C31", "C35", "C37"],
    Dodge: ["Challenger", "Charger", "Durango", "Ram"],
    Ferrari: ["488", "Portofino", "Roma", "F8", "812", "SF90"],
    Fiat: ["500", "Panda", "Tipo", "Punto", "Doblo", "500X", "500L"],
    Fisker: ["Karma", "Ocean"],
    Ford: ["Fiesta", "Focus", "Mustang", "Kuga", "Edge", "Explorer", "Ranger", "F-150"],
    Honda: ["Civic", "Accord", "CR-V", "Jazz", "HR-V", "Pilot", "Fit"],
    Hummer: ["H1", "H2", "H3", "EV"],
    Hyundai: ["i10", "i20", "i30", "Elantra", "Tucson", "Santa Fe", "Kona"],
    Ineos: ["Grenadier"],
    Infiniti: ["Q50", "Q60", "QX50", "QX60", "QX80"],
    Isuzu: ["D-Max", "MU-X", "Trooper", "Rodeo"],
    Jaguar: ["XE", "XF", "XJ", "F-Pace", "E-Pace", "F-Type"],
    Jeep: ["Wrangler", "Cherokee", "Grand Cherokee", "Renegade", "Compass", "Gladiator"],
    "KG Mobility": ["Tivoli", "Rexton", "Korando", "Musso"],
    Kia: ["Rio", "Ceed", "Sportage", "Sorento", "Stonic", "Stinger", "Niro"],
    Lada: ["Niva", "Granta", "Vesta", "XRay"],
    Lamborghini: ["Aventador", "Huracan", "Urus"],
    Lancia: ["Ypsilon", "Delta", "Thema"],
    "Land Rover": ["Defender", "Discovery", "Range Rover", "Evoque", "Velar"],
    Lexus: ["IS", "ES", "GS", "LS", "RX", "NX", "UX"],
    Ligier: ["JS50", "JS60", "Pulse 3"],
    Lincoln: ["Navigator", "Aviator", "Corsair", "Continental"],
    Lotus: ["Elise", "Exige", "Evora"],
    Lucid: ["Air", "Gravity"],
    "Lynk&Co": ["01", "02", "03", "05", "06", "09"],
    Maserati: ["Ghibli", "Quattroporte", "Levante", "GranTurismo"],
    Mazda: ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-5", "MX-5"],
    McLaren: ["570S", "720S", "GT", "P1"],
    Maybach: ["S-className", "GLS"],
    "Merceds-Benz": ["A-className", "C-className", "E-className", "S-className", "GLA", "GLC", "GLE", "GLS", "G-className", "Vito", "Sprinter"],
    MG: ["ZS", "HS", "5", "MG4"],
    Microlinio: ["Lite", "Pioneer", "Ranger"],
    Mini: ["Cooper", "Clubman", "Countryman"],
    Mitsubishi: ["Mirage", "Outlander", "ASX", "L200"],
    Microcar: ["M.Go", "M8", "Dué"],
    Morgan: ["Plus Four", "Plus Six"],
    Nissan: ["Micra", "Juke", "Qashqai", "X-Trail", "Leaf", "Navara"],
    Opel: ["Corsa", "Astra", "Insignia", "Mokka", "Crossland", "Grandland"],
    Peugeot: ["208", "308", "508", "2008", "3008", "5008"],
    Plymouth: ["Barracuda", "Fury", "Road Runner"],
    Pontiac: ["Firebird", "GTO", "Bonneville"],
    Porsche: ["911", "Cayenne", "Panamera", "Taycan", "Macan", "Boxster", "Cayman"],
    Renault: ["Clio", "Megane", "Captur", "Kadjar", "Koleos", "Talisman"],
    "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Cullinan"],
    Rover: ["200", "400", "600", "800"],
    Saab: ["9-3", "9-5", "900", "9000"],
    Seat: ["Ibiza", "Leon", "Ateca", "Arona", "Tarraco"],
    Skoda: ["Fabia", "Octavia", "Superb", "Kodiaq", "Karoq"],
    Smart: ["ForTwo", "ForFour"],
    SsangYong: ["Tivoli", "Korando", "Rexton", "Musso"],
    Skywell: ["ET5", "ET6"],
    Subaru: ["Impreza", "Legacy", "Outback", "Forester", "XV", "WRX"],
    Suzuki: ["Swift", "Vitara", "S-Cross", "Jimny"],
    Tesla: ["Model S", "Model 3", "Model X", "Model Y"],
    Tata: ["Nexon", "Safari", "Harrier"],
    Tazzari: ["Zero", "Em2"],
    Toyota: ["Yaris", "Corolla", "Camry", "RAV4", "Land Cruiser", "Hilux"],
    Trabant: ["601", "P50", "1.1"],
    Triumph: ["Herald", "TR6", "Spitfire"],
    Vauxhall: ["Corsa", "Astra", "Insignia"],
    Volkswagen: ["Golf", "Passat", "Polo", "Tiguan", "Touareg", "T-Roc", "ID.3", "ID.4"],
    Volvo: ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"],
    Weismann: ["MF3", "MF4", "GT"],
    "Alte marci": ["Dacia 1300", "ARO M461", "ARO 244"],
    JAC: ["S2", "S3", "S5"],
    SWM: ["G01", "X3", "X7"],
    Forthing: ["T5 EVO", "Thunder EV"],
    XEV: ["Yoyo"],
};
export const bodies = ["Cabrio", "Sedan", "Coupe", "Pickup", "HatchBack", "Break", "Off-road", "Minibus", "Monovolum", "SUV" ];
export const colors = [
    "Almond", "Alpine White", "Amethyst", "Anthracite", "Aqua", "Arctic White", "Azure", "Beige", "Black", 
      "Black Cherry", "Black Diamond", "Black Pearl", "Black Sapphire", "Blue", "Blue Diamond", "Blue Metallic", 
      "Brilliant Black", "Brilliant Blue", "Bronze", "Brown", "Burgundy", "Candy Apple Red", "Carbon Black", 
      "Cavansite Blue", "Champagne", "Charcoal", "Cobalt Blue", "Copper", "Cream", "Crimson", "Crystal White", 
      "Dark Blue", "Dark Green", "Dark Red", "Daytona Gray", "Deep Black Pearl", "Deep Blue", "Deep Green", 
      "Desert Sand", "Designo Diamond White", "Designo Manufaktur", "Designo Selenite Gray Magno", 
      "Diamond Silver", "Dove Gray", "Electric Blue", "Emerald Green", "Estoril Blue", "Floret Silver", 
      "Forest Green", "Frozen Brilliant White", "Frozen Silver", "Frozen White", "Glacier Blue", "Glacier White", 
      "Gold", "Graphite", "Gray", "Green", "Gunmetal", "Ice Blue", "Ibis White", "Indium Gray", "Iridium Silver", 
      "Ivory", "Jet Black", "Lapis Blue", "Lava Orange", "Lavender", "Le Mans Blue", "Lime Green", 
      "Limestone Gray", "Magenta", "Maroon", "Matte Black", "Melbourne Red", "Midnight Blue", "Mineral White", 
      "Mint Green", "Misano Red", "Moonlight Silver", "Mojave Silver", "Mythos Black", "Nardo Gray", 
      "Navarra Blue", "Navy Blue", "Night Blue", "Ocean Blue", "Olive Green", "Onyx Black", "Orange", 
      "Oryx White Pearl", "Pale Blue", "Pearl White", "Phantom Black", "Pink", "Platinum", "Platinum Gray", 
      "Polar White", "Pure White", "Purple", "Racing Green", "Raven Black", "Red", "Reflex Silver", 
      "Riviera Blue", "Rose Gold", "Ruby Red", "Saffron", "San Marino Blue", "Sand", "Sapphire Black", 
      "Sapphire Blue", "Sepang Blue", "Shadow Black", "Silver", "Sky Blue", "Slate Gray", "Slenite Gray", 
      "Snow White", "Sophisto Gray", "Steel Blue", "Storm Gray", "Sunset Orange", "Super White", "Suzuka Gray", 
      "Tan", "Tango Red", "Tanzanite Blue", "Teal", "Titanium", "Tornado Red", "Turquoise", "Vesuvius Gray", 
      "Viper Green", "White", "Yellow"
  ];
  export const countries = [
    "Albania", "Andorra", "Austria", "Belarus", "Belgium", "Bosnia and Herzegovina", "Bulgaria", "Croatia", 
    "Cyprus", "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", 
    "Iceland", "Ireland", "Italy", "Kosovo", "Latvia", "Liechtenstein", "Lithuania", "Luxembourg", "Malta", 
    "Moldova", "Monaco", "Montenegro", "Netherlands", "North Macedonia", "Norway", "Poland", "Portugal", 
    "Romania", "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland", "Ukraine", 
    "United Kingdom", "Vatican City"
];

export const regionsByCountry = {
  Albania: ["Berat", "Dibër", "Durrës", "Elbasan", "Fier", "Gjirokastër", "Korçë", "Kukës", "Lezhë", "Shkodër", "Tiranë", "Vlorë"],
  Andorra: ["Andorra la Vella", "Canillo", "Encamp", "Escaldes-Engordany", "La Massana", "Ordino", "Sant Julià de Lòria"],
  Austria: ["Burgenland", "Carinthia", "Lower Austria", "Upper Austria", "Salzburg", "Styria", "Tyrol", "Vorarlberg", "Vienna"],
  Belarus: ["Brest", "Gomel", "Grodno", "Minsk", "Mogilev", "Vitebsk"],
  Belgium: ["Antwerp", "East Flanders", "Flemish Brabant", "Hainaut", "Liège", "Limburg", "Luxembourg", "Namur", "Walloon Brabant", "West Flanders"],
  BosniaAndHerzegovina: ["Federacija Bosne i Hercegovine", "Republika Srpska", "Brčko District"],
  Bulgaria: ["Blagoevgrad", "Burgas", "Dobrich", "Gabrovo", "Haskovo", "Kardzhali", "Kyustendil", "Lovech", "Montana", "Pazardzhik", "Pernik", "Pleven", "Plovdiv", "Razgrad", "Ruse", "Shumen", "Silistra", "Sliven", "Smolyan", "Sofia", "Stara Zagora", "Targovishte", "Varna", "Veliko Tarnovo", "Vidin", "Vratsa", "Yambol"],
  Croatia: ["Bjelovar-Bilogora", "Brod-Posavina", "Dubrovnik-Neretva", "Istria", "Karlovac", "Koprivnica-Križevci", "Krapina-Zagorje", "Lika-Senj", "Međimurje", "Osijek-Baranja", "Požega-Slavonia", "Primorje-Gorski Kotar", "Sisak-Moslavina", "Split-Dalmatia", "Šibenik-Knin", "Varaždin", "Virovitica-Podravina", "Vukovar-Srijem", "Zadar", "Zagreb"],
  Cyprus: ["Famagusta", "Kyrenia", "Larnaca", "Limassol", "Nicosia", "Paphos"],
  CzechRepublic: ["Central Bohemian", "South Bohemian", "Pilsen", "Karlovy Vary", "Ústí nad Labem", "Liberec", "Hradec Králové", "Pardubice", "Vysočina", "South Moravian", "Olomouc", "Zlín", "Moravian-Silesian"],
  Denmark: ["Capital", "Central Denmark", "North Denmark", "Zealand", "Southern Denmark"],
  Estonia: ["Harju", "Hiiu", "Ida-Viru", "Jõgeva", "Järva", "Lääne", "Lääne-Viru", "Põlva", "Pärnu", "Rapla", "Saare", "Tartu", "Valga", "Viljandi", "Võru"],
  Finland: ["Åland", "Central Finland", "Central Ostrobothnia", "Kainuu", "Kanta-Häme", "Kymenlaakso", "Lapland", "North Karelia", "North Ostrobothnia", "Northern Savonia", "Ostrobothnia", "Päijät-Häme", "Pirkanmaa", "Satakunta", "South Karelia", "South Ostrobothnia", "Southern Savonia", "Uusimaa", "Varsinais-Suomi"],
  France: ["Auvergne-Rhône-Alpes", "Bourgogne-Franche-Comté", "Brittany", "Centre-Val de Loire", "Corsica", "Grand Est", "Hauts-de-France", "Île-de-France", "Normandy", "Nouvelle-Aquitaine", "Occitanie", "Pays de la Loire", "Provence-Alpes-Côte d'Azur"],
  Germany: ["Baden-Württemberg", "Bavaria", "Berlin", "Brandenburg", "Bremen", "Hamburg", "Hesse", "Lower Saxony", "Mecklenburg-Vorpommern", "North Rhine-Westphalia", "Rhineland-Palatinate", "Saarland", "Saxony", "Saxony-Anhalt", "Schleswig-Holstein", "Thuringia"],
  Greece: ["Achaea", "Aetolia-Acarnania", "Arcadia", "Argolis", "Attica", "Boeotia", "Central Macedonia", "Crete", "Dodecanese", "East Macedonia and Thrace", "Euboea", "Evrytania", "Ionian Islands", "Laconia", "Larissa", "Messenia", "North Aegean", "Peloponnese", "South Aegean", "Thessaloniki", "West Greece", "West Macedonia"],
  Hungary: ["Bács-Kiskun", "Baranya", "Békés", "Borsod-Abaúj-Zemplén", "Budapest", "Csongrád-Csanád", "Fejér", "Győr-Moson-Sopron", "Hajdú-Bihar", "Heves", "Jász-Nagykun-Szolnok", "Komárom-Esztergom", "Nógrád", "Pest", "Somogy", "Szabolcs-Szatmár-Bereg", "Tolna", "Vas", "Veszprém", "Zala"],
  Iceland: ["Capital Region", "Southern Peninsula", "Westfjords", "Western Region", "Northwest Region", "Northeastern Region", "Eastern Region", "Southern Region"],
  Ireland: ["Carlow", "Cavan", "Clare", "Cork", "Donegal", "Dublin", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Waterford", "Westmeath", "Wexford", "Wicklow"],
  Italy: ["Abruzzo", "Basilicata", "Calabria", "Campania", "Emilia-Romagna", "Friuli Venezia Giulia", "Lazio", "Liguria", "Lombardy", "Marche", "Molise", "Piedmont", "Apulia", "Sardinia", "Sicily", "Tuscany", "Trentino-South Tyrol", "Umbria", "Aosta Valley", "Veneto"],
  Kosovo: ["Ferizaj", "Gjakova", "Gjilan", "Mitrovica", "Peja", "Pristina", "Prizren"],
  Latvia: ["Kurzeme", "Latgale", "Riga", "Vidzeme", "Zemgale"],
  Liechtenstein: ["Balzers", "Eschen", "Gamprin", "Mauren", "Planken", "Ruggell", "Schaan", "Schellenberg", "Triesen", "Triesenberg", "Vaduz"],
  Lithuania: ["Alytus", "Kaunas", "Klaipėda", "Marijampolė", "Panevėžys", "Šiauliai", "Tauragė", "Telšiai", "Utena", "Vilnius"],
  Luxembourg: ["Diekirch", "Grevenmacher", "Luxembourg"],
  Malta: ["Gozo", "Malta"],
  Moldova: ["Bălți", "Bender", "Chișinău", "Gagauzia", "Transnistria"],
  Monaco: ["Monaco-Ville", "Fontvieille", "La Condamine", "Monte Carlo"],
  Montenegro: ["Andrijevica", "Bar", "Berane", "Bijelo Polje", "Budva", "Cetinje", "Danilovgrad", "Herceg Novi", "Kolašin", "Kotor", "Mojkovac", "Nikšić", "Petnjica", "Plav", "Pljevlja", "Plužine", "Podgorica", "Rožaje", "Šavnik", "Tivat", "Ulcinj", "Žabljak"],
  Netherlands: ["Drenthe", "Flevoland", "Friesland", "Gelderland", "Groningen", "Limburg", "North Brabant", "North Holland", "Overijssel", "South Holland", "Utrecht", "Zeeland"],
  NorthMacedonia: ["Eastern", "Northeastern", "Pelagonia", "Polog", "Skopje", "Southeastern", "Southwestern", "Vardar"],
  Norway: ["Agder", "Innlandet", "Møre og Romsdal", "Nordland", "Oslo", "Rogaland", "Troms og Finnmark", "Trøndelag", "Vestfold og Telemark", "Vestland", "Viken"],
  Poland: ["Greater Poland", "Kuyavian-Pomeranian", "Lesser Poland", "Łódź", "Lower Silesian", "Lublin", "Lubusz", "Masovian", "Opole", "Podlaskie", "Pomeranian", "Silesian", "Świętokrzyskie", "Warmian-Masurian", "West Pomeranian"],
  Portugal: ["Aveiro", "Beja", "Braga", "Bragança", "Castelo Branco", "Coimbra", "Évora", "Faro", "Guarda", "Leiria", "Lisbon", "Portalegre", "Porto", "Santarém", "Setúbal", "Viana do Castelo", "Vila Real", "Viseu", "Azores", "Madeira"],
  Romania: ["Alba", "Arad", "Argeș", "Bacău", "Bihor", "Bistrița-Năsăud", "Botoșani", "Brașov", "Brăila", "București", "Buzău", "Caraș-Severin", "Călărași", "Cluj", "Constanța", "Covasna", "Dâmbovița", "Dolj", "Galați", "Giurgiu", "Gorj", "Harghita", "Hunedoara", "Ialomița", "Iași", "Ilfov", "Maramureș", "Mehedinți", "Mureș", "Neamț", "Olt", "Prahova", "Satu Mare", "Sălaj", "Sibiu", "Suceava", "Teleorman", "Timiș", "Tulcea", "Vâlcea", "Vaslui", "Vrancea"],
  Russia: ["Adygea", "Altai Krai", "Altai Republic", "Amur Oblast", "Arkhangelsk Oblast", "Astrakhan Oblast", "Bashkortostan", "Belgorod Oblast", "Bryansk Oblast", "Buryatia", "Chechen Republic", "Chelyabinsk Oblast", "Chukotka Autonomous Okrug", "Chuvashia", "Dagestan", "Ingushetia", "Irkutsk Oblast", "Ivanovo Oblast", "Jewish Autonomous Oblast", "Kabardino-Balkaria", "Kaliningrad Oblast", "Kalmykia", "Kaluga Oblast", "Kamchatka Krai", "Karachay-Cherkessia", "Karelia", "Kemerovo Oblast", "Khabarovsk Krai", "Khakassia", "Khanty-Mansi Autonomous Okrug", "Kirov Oblast", "Komi Republic", "Kostroma Oblast", "Krasnodar Krai", "Krasnoyarsk Krai", "Kurgan Oblast", "Kursk Oblast", "Leningrad Oblast", "Lipetsk Oblast", "Magadan Oblast", "Mari El Republic", "Mordovia", "Moscow", "Moscow Oblast", "Murmansk Oblast", "Nenets Autonomous Okrug", "Nizhny Novgorod Oblast", "North Ossetia–Alania", "Novgorod Oblast", "Novosibirsk Oblast", "Omsk Oblast", "Orenburg Oblast", "Oryol Oblast", "Penza Oblast", "Perm Krai", "Primorsky Krai", "Pskov Oblast", "Rostov Oblast", "Ryazan Oblast", "Saint Petersburg", "Sakha Republic", "Sakhalin Oblast", "Samara Oblast", "Saratov Oblast", "Smolensk Oblast", "Stavropol Krai", "Sverdlovsk Oblast", "Tambov Oblast", "Tatarstan", "Tomsk Oblast", "Tula Oblast", "Tver Oblast", "Tyumen Oblast", "Udmurtia", "Ulyanovsk Oblast", "Vladimir Oblast", "Volgograd Oblast", "Vologda Oblast", "Voronezh Oblast", "Yamalo-Nenets Autonomous Okrug", "Yaroslavl Oblast", "Zabaykalsky Krai"],
  "San Marino": ["Acquaviva", "Borgo Maggiore", "Chiesanuova", "Domagnano", "Faetano", "Fiorentino", "Montegiardino", "San Marino Città", "Serravalle"],
  Serbia: ["Belgrade", "Šumadija", "Western Serbia", "Vojvodina", "Southern and Eastern Serbia"],
  Slovakia: ["Banská Bystrica", "Bratislava", "Košice", "Nitra", "Prešov", "Trenčín", "Trnava", "Žilina"],
  Slovenia: ["Ajdovščina", "Bled", "Celje", "Cerklje na Gorenjskem", "Domžale", "Grosuplje", "Hrastnik", "Idrija", "Ilirska Bistrica", "Izola", "Jesenice", "Kamnik", "Koper", "Kranj", "Krško", "Laško", "Ljubljana", "Ljutomer", "Logatec", "Maribor", "Medvode", "Murska Sobota", "Nova Gorica", "Novo Mesto", "Ormož", "Piran", "Postojna", "Ptuj", "Radlje ob Dravi", "Radovljica", "Ravne na Koroškem", "Sežana", "Slovenj Gradec", "Slovenska Bistrica", "Slovenske Konjice", "Šentjur", "Škofja Loka", "Šoštanj", "Tolmin", "Trbovlje", "Trebnje", "Velenje", "Vrhnika", "Žalec"],
  Spain: ["Andalusia", "Aragon", "Asturias", "Balearic Islands", "Basque Country", "Canary Islands", "Cantabria", "Castile and León", "Castile-La Mancha", "Catalonia", "Extremadura", "Galicia", "La Rioja", "Madrid", "Murcia", "Navarre", "Valencian Community"],
  Sweden: ["Blekinge", "Dalarna", "Gävleborg", "Gotland", "Halland", "Jämtland", "Jönköping", "Kalmar", "Kronoberg", "Norrbotten", "Örebro", "Östergötland", "Skåne", "Södermanland", "Stockholm", "Uppsala", "Värmland", "Västerbotten", "Västernorrland", "Västmanland", "Västra Götaland"],
  Switzerland: ["Aargau", "Appenzell Ausserrhoden", "Appenzell Innerrhoden", "Basel-Landschaft", "Basel-Stadt", "Bern", "Fribourg", "Geneva", "Glarus", "Graubünden", "Jura", "Lucerne", "Neuchâtel", "Nidwalden", "Obwalden", "Schaffhausen", "Schwyz", "Solothurn", "St. Gallen", "Ticino", "Thurgau", "Uri", "Valais", "Vaud", "Zug", "Zürich"],
  Turkey: ["Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Aksaray", "Amasya", "Ankara", "Antalya", "Ardahan", "Artvin", "Aydın", "Balıkesir", "Bartın", "Batman", "Bayburt", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Düzce", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkâri", "Hatay", "Iğdır", "Isparta", "Istanbul", "İzmir", "Kahramanmaraş", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kilis", "Kırıkkale", "Kırklareli", "Kırşehir", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Mardin", "Mersin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Osmaniye", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Şanlıurfa", "Şırnak", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak"],
  Ukraine: ["Cherkasy", "Chernihiv", "Chernivtsi", "Dnipropetrovsk", "Donetsk", "Ivano-Frankivsk", "Kharkiv", "Kherson", "Khmelnytskyi", "Kyiv", "Kirovohrad", "Luhansk", "Lviv", "Mykolaiv", "Odessa", "Poltava", "Rivne", "Sumy", "Ternopil", "Vinnytsia", "Volyn", "Zakarpattia", "Zaporizhzhia", "Zhytomyr"],
  "United Kingdom": ["England", "Northern Ireland", "Scotland", "Wales"],
  "Vatican City": ["Vatican City"]
};

export const cityByRegion = {
  Berat: ["Berat", "Poliçan", "Kuçovë", "Çorovodë", "Ura Vajgurore", "Bogovë"],
  Dibër: ["Peshkopi", "Bulqizë", "Kastriot", "Maçurishtë", "Muhurr"],
  Durrës: ["Durrës", "Shijak", "Xhafzotaj", "Katund i Ri", "Sukth", "Manzë"],
  Elbasan: ["Elbasan", "Cërrik", "Peqin", "Belsh", "Librazhd", "Gramsh"],
  Fier: ["Fier", "Patos", "Roskovec", "Ballsh", "Divjakë", "Frakull"],
  Gjirokastër: ["Gjirokastër", "Libohovë", "Tepelenë", "Memaliaj", "Përmet", "Këlcyrë"],
  Korçë: ["Korçë", "Pogradec", "Ersekë", "Maliq", "Kolonjë", "Bilisht"],
  Kukës: ["Kukës", "Tropojë", "Has", "Krumë", "Shishtavec", "Bajram Curri"],
  Lezhë: ["Lezhë", "Laç", "Milot", "Rrëshen", "Shëngjin", "Balldre"],
  Shkodër: ["Shkodër", "Vau i Dejës", "Pukë", "Fushë-Arrëz", "Malësia e Madhe"],
  Tiranë: ["Tirana", "Kamëz", "Vorë", "Kavajë", "Rrogozhinë", "Ndroq"],
  Vlorë: ["Vlorë", "Sarandë", "Orikum", "Selenicë", "Delvinë", "Himarë"],
  Andorra_la_Vella: ["Andorra la Vella", "Santa Coloma", "Escaldes-Engordany"],
  Canillo: ["Canillo", "El Tarter", "Soldeu", "Incles"],
  Encamp: ["Encamp", "Pas de la Casa", "Vila"],
  "Escaldes-Engordany": ["Escaldes", "Engordany", "Els Vilars"],
  La_Massana: ["La Massana", "Arinsal", "Pal"],
  Ordino: ["Ordino", "El Serrat", "Llorts"],
  Sant_Julia_de_Loria: ["Sant Julià de Lòria", "Aixirivall", "Nagol"],
  Burgenland: ["Eisenstadt", "Rust", "Neusiedl am See", "Oberwart", "Güssing"],
  Carinthia: ["Klagenfurt", "Villach", "Wolfsberg", "Spittal an der Drau"],
  Lower_Austria: ["St. Pölten", "Krems", "Amstetten", "Baden"],
  Salzburg: ["Salzburg", "Hallein", "Saalfelden", "Bischofshofen"],
  Styria: ["Graz", "Leoben", "Bruck an der Mur", "Kapfenberg"],
  Tyrol: ["Innsbruck", "Kufstein", "Schwaz", "Lienz"],
  Upper_Austria: ["Linz", "Wels", "Steyr", "Gmunden"],
  Vienna: ["Vienna"],
  Vorarlberg: ["Bregenz", "Dornbirn", "Feldkirch", "Bludenz"],
  Brest: ["Brest", "Baranovichi", "Pinsk", "Kobryn", "Luninets"],
  Gomel: ["Gomel", "Mozyr", "Zhlobin", "Rechytsa", "Svetlogorsk"],
  Grodno: ["Grodno", "Lida", "Slonim", "Volkovysk", "Ostrovets"],
  Minsk: ["Minsk", "Zaslawye", "Barysaw", "Molodechno", "Salihorsk"],
  Mogilev: ["Mogilev", "Babruysk", "Asipovichy", "Krychaw"],
  Vitebsk: ["Vitebsk", "Orsha", "Polotsk", "Novopolotsk", "Hlybokaye"],
  Antwerp: ["Antwerp", "Mechelen", "Turnhout", "Geel"],
  East_Flanders: ["Ghent", "Aalst", "Sint-Niklaas", "Eeklo"],
  Flemish_Brabant: ["Leuven", "Vilvoorde", "Halle", "Diest"],
  Hainaut: ["Charleroi", "Mons", "La Louvière", "Tournai"],
  Liege: ["Liège", "Verviers", "Seraing", "Huy"],
  Limburg: ["Hasselt", "Genk", "Sint-Truiden", "Maaseik"],
  Luxembourg: ["Arlon", "Bastogne", "Marche-en-Famenne", "Neufchâteau"],
  Namur: ["Namur", "Dinant", "Gembloux", "Philippeville"],
  Walloon_Brabant: ["Wavre", "Nivelles", "Ottignies-Louvain-la-Neuve"],
  Brussels: ["Brussels"],
  "Una-Sana": ["Bihać", "Cazin", "Sanski Most", "Bosanski Petrovac"],
  Posavina: ["Orašje", "Odžak", "Domaljevac"],
  Tuzla: ["Tuzla", "Živinice", "Lukavac", "Srebrenik"],
  "Zenica-Doboj": ["Zenica", "Visoko", "Zavidovići", "Maglaj"],
  Sarajevo: ["Sarajevo", "Ilidža", "Vogošća", "Hadžići"],
  "Herzegovina-Neretva": ["Mostar", "Čapljina", "Jablanica", "Stolac"],
  West_Herzegovina: ["Široki Brijeg", "Posušje", "Ljubuški", "Grude"],
  Canton_10: ["Livno", "Tomislavgrad", "Kupres", "Drvar"],
  Brčko_District: ["Brčko"],
  Blagoevgrad: ["Blagoevgrad", "Sandanski", "Petrich", "Gotse Delchev"],
  Burgas: ["Burgas", "Pomorie", "Nesebar", "Sozopol"],
  Dobrich: ["Dobrich", "Balchik", "Kavarna", "Tervel"],
  Gabrovo: ["Gabrovo", "Dryanovo", "Tryavna", "Sevlievo"],
  Haskovo: ["Haskovo", "Dimitrovgrad", "Harmanli", "Svilengrad"],
  Kardzhali: ["Kardzhali", "Momchilgrad", "Ardino", "Krumovgrad"],
  Kyustendil: ["Kyustendil", "Dupnitsa", "Bobov Dol", "Sapareva Banya"],
  Lovech: ["Lovech", "Troyan", "Teteven", "Lukovit"],
  Montana: ["Montana", "Lom", "Berkovitsa", "Varshets"],
  Pazardzhik: ["Pazardzhik", "Velingrad", "Panagyurishte", "Septemvri"],
  Pernik: ["Pernik", "Radomir", "Breznik", "Trun"],
  Pleven: ["Pleven", "Cherven Bryag", "Nikopol", "Knezha"],
  Plovdiv: ["Plovdiv", "Asenovgrad", "Karlovo", "Sopot"],
  Razgrad: ["Razgrad", "Isperih", "Kubrat", "Zavet"],
  Ruse: ["Ruse", "Byala", "Dve Mogili", "Slivo Pole"],
  Shumen: ["Shumen", "Novi Pazar", "Veliki Preslav", "Smyadovo"],
  Silistra: ["Silistra", "Tutrakan", "Dulovo", "Alfatar"],
  Sliven: ["Sliven", "Nova Zagora", "Kotel", "Tvarditsa"],
  Smolyan: ["Smolyan", "Chepelare", "Madan", "Devin"],
  Sofia: ["Sofia", "Bankya", "Elin Pelin", "Ihtiman"],
  Stara_Zagora: ["Stara Zagora", "Kazanalak", "Radnevo", "Gurkovo"],
  Targovishte: ["Targovishte", "Omurtag", "Opaka", "Popovo"],
  Varna: ["Varna", "Devnya", "Provadia", "Aksakovo"],
  Veliko_Tarnovo: ["Veliko Tarnovo", "Gorna Oryahovitsa", "Svishtov", "Pavlikeni"],
  Vidin: ["Vidin", "Belogradchik", "Kula", "Dimovo"],
  Vratsa: ["Vratsa", "Mezdra", "Berkovitsa", "Kozloduy"],
  Yambol: ["Yambol", "Elhovo", "Straldzha", "Bolyarovo"],
  Zagreb: ["Zagreb", "Samobor", "Velika Gorica", "Zaprešić"],
  Split_Dalmatia: ["Split", "Trogir", "Sinj", "Makarska"],
  Istria: ["Pula", "Rovinj", "Poreč", "Labin"],
  Dubrovnik_Neretva: ["Dubrovnik", "Metković", "Ploče", "Korčula"],
  Šibenik_Knin: ["Šibenik", "Knin", "Drniš", "Skradin"],
  Varaždin: ["Varaždin", "Lepoglava", "Ivanec", "Novi Marof"],
  Krapina_Zagorje: ["Krapina", "Pregrada", "Zabok", "Oroslavje"],
  Koprivnica_Križevci: ["Koprivnica", "Križevci", "Đurđevac", "Molve"],
  Međimurje: ["Čakovec", "Mursko Središće", "Prelog", "Donja Dubrava"],
  Bjelovar_Bilogora: ["Bjelovar", "Daruvar", "Garešnica", "Čazma"],
  Osijek_Baranja: ["Osijek", "Đakovo", "Beli Manastir", "Valpovo"],
  Virovitica_Podravina: ["Virovitica", "Slatina", "Orahovica", "Pitomača"],
  Vukovar_Syrmia: ["Vukovar", "Vinkovci", "Županja", "Ilok"],
  Nicosia: ["Nicosia", "Strovolos", "Lakatamia", "Latsia"],
  Limassol: ["Limassol", "Mesa Geitonia", "Agios Athanasios"],
  Larnaca: ["Larnaca", "Aradippou", "Oroklini"],
  Paphos: ["Paphos", "Geroskipou", "Peyia"],
  Famagusta: ["Famagusta", "Paralimni", "Ayia Napa"],
  Prague: ["Prague"],
  Central_Bohemian: ["Kladno", "Mladá Boleslav", "Benešov", "Příbram"],
  South_Moravian: ["Brno", "Znojmo", "Blansko", "Hodonín"],
  Moravian_Silesian: ["Ostrava", "Opava", "Frýdek-Místek", "Třinec"],
  Hradec_Kralove: ["Hradec Králové", "Náchod", "Trutnov", "Jičín"],
  Liberec: ["Liberec", "Česká Lípa", "Jablonec nad Nisou"],
  Olomouc: ["Olomouc", "Přerov", "Prostějov"],
  Pardubice: ["Pardubice", "Chrudim", "Ústí nad Orlicí"],
  Plzen: ["Plzeň", "Klatovy", "Domažlice"],
  Usti_nad_Labem: ["Ústí nad Labem", "Teplice", "Chomutov"],
  Vysočina: ["Jihlava", "Havlíčkův Brod", "Žďár nad Sázavou"],
  Zlin: ["Zlín", "Uherské Hradiště", "Vsetín"],
  Capital: ["Copenhagen", "Frederiksberg", "Hvidovre", "Gentofte"],
  Central_Denmark: ["Aarhus", "Randers", "Viborg", "Silkeborg"],
  North_Denmark: ["Aalborg", "Hjørring", "Frederikshavn", "Brønderslev"],
  Zealand: ["Roskilde", "Næstved", "Slagelse", "Helsingør"],
  Southern_Denmark: ["Odense", "Esbjerg", "Vejle", "Kolding"],
  Azuay: ["Cuenca", "Gualaceo", "Sigsig", "Paute", "Nabón"],
  Bolívar: ["Guaranda", "San Miguel", "Chillanes", "Echeandía"],
  Carchi: ["Tulcán", "San Gabriel", "El Ángel", "Mira"],
  Chimborazo: ["Riobamba", "Guano", "Alausí", "Colta"],
  Cotopaxi: ["Latacunga", "Salcedo", "Saquisilí", "Pujilí"],
  El_Oro: ["Machala", "Santa Rosa", "Huaquillas", "Pasaje"],
  Esmeraldas: ["Esmeraldas", "Atacames", "Quinindé", "San Lorenzo"],
  Galápagos: ["Puerto Ayora", "Puerto Baquerizo Moreno", "Puerto Villamil"],
  Guayas: ["Guayaquil", "Daule", "Milagro", "Samborondón"],
  Imbabura: ["Ibarra", "Otavalo", "Cotacachi", "Antonio Ante"],
  Loja: ["Loja", "Catamayo", "Macará", "Puyango"],
  Los_Ríos: ["Babahoyo", "Quevedo", "Ventanas", "Buena Fe"],
  Manabí: ["Portoviejo", "Manta", "Jipijapa", "Chone"],
  Morona_Santiago: ["Macas", "Gualaquiza", "Santiago", "Sucúa"],
  Napo: ["Tena", "Archidona", "El Chaco", "Quijos"],
  Orellana: ["Coca", "Dayuma", "Loreto", "Nuevo Rocafuerte"],
  Pastaza: ["Puyo", "Shell", "Mera", "Arajuno"],
  Pichincha: ["Quito", "Cayambe", "Mejía", "Pedro Moncayo"],
  Santa_Elena: ["Santa Elena", "Salinas", "La Libertad", "Anconcito"],
  Santo_Domingo_de_los_Tsachilas: ["Santo Domingo", "Alluriquín", "Puerto Limón"],
  Sucumbíos: ["Nueva Loja", "Shushufindi", "Cascales", "Putumayo"],
  Tungurahua: ["Ambato", "Baños", "Pelileo", "Píllaro"],
  Zamora_Chinchipe: ["Zamora", "Yantzaza", "El Pangui", "Centinela del Cóndor"], 
  Cairo: ["Cairo", "Helwan", "Nasr City", "Maadi"],
  Alexandria: ["Alexandria", "Borg El Arab", "El Agamy"],
  Giza: ["Giza", "October City", "Sheikh Zayed"],
  Aswan: ["Aswan", "Edfu", "Kom Ombo"],
  Asyut: ["Asyut", "Dairut", "Abnoub"],
  Beheira: ["Damanhur", "Kafr El Dawwar", "Rashid", "Itay El Barud"],
  Beni_Suef: ["Beni Suef", "Ihnasya", "Biba", "El Fashn"],
  Dakahlia: ["Mansoura", "Talkha", "Mit Ghamr", "Dikirnis"],
  Damietta: ["Damietta", "Faraskur", "New Damietta"],
  Faiyum: ["Faiyum", "Ibshway", "Sinnuris"],
  Gharbia: ["Tanta", "Al Mahalla al-Kubra", "Kafr El Zayat"],
  Ismailia: ["Ismailia", "Fayed", "Al Qantara"],
  Kafr_El_Sheikh: ["Kafr El Sheikh", "Disuq", "El Hamoul"],
  Luxor: ["Luxor", "Armant", "Esna"],
  Matruh: ["Mersa Matruh", "El Alamein", "Sidi Barrani"],
  Minya: ["Minya", "Mallawi", "Beni Mazar", "Maghagha"],
  Monufia: ["Shebeen El Kom", "Menouf", "Sadat City"],
  New_Valley: ["Kharga", "Dakhla", "Farafra"],
  North_Sinai: ["Arish", "Sheikh Zuweid", "Rafah"],
  Port_Said: ["Port Said", "Port Fuad"],
  Qalyubia: ["Banha", "Shibin El Qanater", "Kafr Shukr"],
  Qena: ["Qena", "Nag Hammadi", "Qift"],
  Red_Sea: ["Hurghada", "Safaga", "Ras Ghareb"],
  Sharqia: ["Zagazig", "Belbeis", "Abu Kabir"],
  Sohag: ["Sohag", "Girga", "Tahta"],
  South_Sinai: ["Sharm El Sheikh", "Dahab", "Nuweiba"],
  Suez: ["Suez", "Ataqah", "Ain Sokhna"],
  Ahuachapán: ["Ahuachapán", "Atiquizaya", "Turin", "Concepción de Ataco"],
  Cabañas: ["Sensuntepeque", "Ilobasco", "Victoria", "Jutiapa"],
  Chalatenango: ["Chalatenango", "La Palma", "Dulce Nombre de María"],
  Cuscatlán: ["Cojutepeque", "Suchitoto", "San Pedro Perulapán"],
  La_Libertad: ["Santa Tecla", "Antiguo Cuscatlán", "Quezaltepeque", "Nuevo Cuscatlán"],
  La_Paz: ["Zacatecoluca", "San Luis Talpa", "San Pedro Masahuat"],
  La_Union: ["La Unión", "Santa Rosa de Lima", "Pasaquina", "Intipucá"],
  Morazán: ["San Francisco Gotera", "Osicala", "Jocoro", "Yamabal"],
  San_Miguel: ["San Miguel", "Chapeltique", "Quelepa"],
  San_Salvador: ["San Salvador", "Soyapango", "Ilopango", "Mejicanos"],
  San_Vicente: ["San Vicente", "Tecoluca", "San Ildefonso"],
  Santa_Ana: ["Santa Ana", "Metapán", "Texistepeque"],
  Sonsonate: ["Sonsonate", "Acajutla", "Nahuizalco"],
  Usulután: ["Usulután", "Jiquilisco", "Santiago de María", "Santa Elena"],
  Harju: ["Tallinn", "Maardu", "Saue", "Keila"],
  Hiiu: ["Kärdla", "Kõrgessaare"],
  Ida_Viru: ["Narva", "Kohtla-Järve", "Jõhvi", "Sillamäe"],
  Järva: ["Paide", "Türi", "Järva-Jaani"],
  Jõgeva: ["Jõgeva", "Põltsamaa", "Mustvee"],
  Lääne: ["Haapsalu", "Palivere"],
  Lääne_Viru: ["Rakvere", "Tapa", "Kadrina", "Viru-Jaagupi"],
  Pärnu: ["Pärnu", "Sindi", "Vändra"],
  Põlva: ["Põlva", "Räpina"],
  Rapla: ["Rapla", "Kohila", "Märjamaa"],
  Saare: ["Kuressaare", "Orissaare"],
  Tartu: ["Tartu", "Elva"],
  Valga: ["Valga", "Otepää"],
  Viljandi: ["Viljandi", "Abja-Paluoja"],
  Võru: ["Võru", "Antsla"],
  Addis_Ababa: ["Addis Ababa"],
  Afar: ["Semera", "Asaita", "Logiya"],
  Amhara: ["Bahir Dar", "Gondar", "Dessie", "Debre Berhan"],
  Benishangul_Gumuz: ["Asosa", "Guba"],
  Dire_Dawa: ["Dire Dawa"],
  Gambela: ["Gambela", "Abobo"],
  Harari: ["Harar"],
  Oromia: ["Adama", "Bishoftu", "Jimma", "Shashamane"],
  Sidama: ["Hawassa", "Yirgalem"],
  Somali: ["Jijiga", "Gode", "Shilabo"],
  Southern_Nations: ["Arba Minch", "Sodo", "Hosaena"],
  Tigray: ["Mekelle", "Adigrat", "Shire"],
  Åland: ["Mariehamn", "Jomala"],
  Central_Finland: ["Jyväskylä", "Äänekoski", "Keuruu"],
  Central_Ostrobothnia: ["Kokkola", "Kannus"],
  Kainuu: ["Kajaani", "Sotkamo"],
  Kymenlaakso: ["Kotka", "Kouvola"],
  Lapland: ["Rovaniemi", "Kemi"],
  North_Karelia: ["Joensuu", "Lieksa"],
  North_Ostrobothnia: ["Oulu", "Kuusamo"],
  North_Savo: ["Kuopio", "Iisalmi"],
  Ostrobothnia: ["Vaasa", "Korsholm"],
  Pirkanmaa: ["Tampere", "Nokia"],
  Satakunta: ["Pori", "Rauma"],
  South_Carelia: ["Lappeenranta", "Imatra"],
  South_Ostrobothnia: ["Seinäjoki", "Kauhava"],
  South_Savo: ["Mikkeli", "Savonlinna"],
  Southwest_Finland: ["Turku", "Salo"],
  Uusimaa: ["Helsinki", "Espoo"],
  Auvergne_Rhone_Alpes: ["Lyon", "Grenoble"],
  Bourgogne_Franche_Comté: ["Dijon", "Besançon"],
  Brittany: ["Rennes", "Brest"],
  Centre_Val_de_Loire: ["Orléans", "Tours"],
  Corsica: ["Ajaccio", "Bastia"],
  Grand_Est: ["Strasbourg", "Reims"],
  Hauts_de_France: ["Lille", "Amiens"],
  Ile_de_France: ["Paris", "Versailles"],
  Normandy: ["Rouen", "Caen"],
  Nouvelle_Aquitaine: ["Bordeaux", "Limoges"],
  Occitanie: ["Toulouse", "Montpellier"],
  Pays_de_la_Loire: ["Nantes", "Angers"],
  Provence_Alpes_Côte_d_Azur: ["Marseille", "Nice"],
  Abkhazia: ["Sukhumi", "Gagra", "Gali"],
  Ajara: ["Batumi", "Kobuleti", "Zugdidi"],
  Guria: ["Ozurgeti", "Lanchkhuti", "Chokhatauri"],
  Imereti: ["Kutaisi", "Tskhaltubo", "Zestaponi"],
  Kakheti: ["Telavi", "Signagi", "Lagodekhi"],
  Kvemo_Kartli: ["Rustavi", "Marneuli", "Tsalka"],
  Mtskheta_Mtianeti: ["Mtskheta", "Kazbegi", "Stepantsminda"],
  "Racha-Lechkhumi": ["Ambrolauri", "Oni", "Tsageri"],
  "Samegrelo-Zemo_Svaneti": ["Zugdidi", "Senaki", "Mestia"],
  "Samtskhe-Javakheti": ["Akhaltsikhe", "Aspindza", "Borjomi"],
  Tbilisi: ["Tbilisi"],
  "Baden-Württemberg": ["Stuttgart", "Karlsruhe", "Freiburg", "Heidelberg"],
  Bavaria: ["Munich", "Nuremberg", "Augsburg", "Regensburg"],
  Berlin: ["Berlin"],
  Brandenburg: ["Potsdam", "Cottbus", "Frankfurt (Oder)"],
  Bremen: ["Bremen", "Bremerhaven"],
  Hamburg: ["Hamburg"],
  Hesse: ["Wiesbaden", "Frankfurt", "Darmstadt"],
  Lower_Saxony: ["Hanover", "Braunschweig", "Oldenburg"],
  "Mecklenburg-Vorpommern": ["Rostock", "Greifswald", "Stralsund"],
  "North_Rhine-Westphalia": ["Düsseldorf", "Cologne", "Dortmund"],
  "Rhineland-Palatinate": ["Mainz", "Trier", "Ludwigshafen"],
  Saarland: ["Saarbrücken", "Neunkirchen"],
  Saxony: ["Dresden", "Leipzig", "Chemnitz"],
  "Saxony-Anhalt": ["Magdeburg", "Halle", "Dessau"],
  "Schleswig-Holstein": ["Kiel", "Lübeck", "Flensburg"],
  Thuringia: ["Erfurt", "Jena", "Gera"],
  Greater_Accra: ["Accra", "Tema", "Dodowa"],
  Ashanti: ["Kumasi", "Obuasi", "Konongo"],
  Western: ["Sekondi-Takoradi", "Shama", "Dixcove"],
  Eastern: ["Koforidua", "Akropong", "Aburi"],
  Central: ["Cape Coast", "Elmina", "Winneba"],
  Northern: ["Tamale", "Buipe", "Gushegu"],
  Western_North: ["Sefwi Wiawso", "Bibiani", "Bechem"],
  Bono: ["Sunyani", "Berekum", "Chiraa"],
  Bono_East: ["Techiman", "Nkoranza", "Kintampo"],
  Oti: ["Dambai", "Nkwanta", "Kpassa"],
  Volta: ["Ho", "Keta", "Aflao"],
  Upper_East: ["Bolgatanga", "Bawku", "Navrongo"],
  Upper_West: ["Wa", "Jirapa", "Nandom"],
  Attica: ["Athens", "Piraeus", "Kifisia"],
  Central_Greece: ["Lamia", "Amfissa", "Livadeia"],
  Central_Macedonia: ["Thessaloniki", "Katerini", "Veria"],
  Crete: ["Heraklion", "Chania", "Rethymno"],
  East_Macedonia_and_Thrace: ["Kavala", "Xanthi", "Drama"],
  Epirus: ["Ioannina", "Preveza", "Arta"],
  Ionian_Islands: ["Corfu", "Zakynthos", "Kefalonia"],
  North_Aegean: ["Mytilene", "Chios", "Samos"],
  Peloponnese: ["Patras", "Kalamata", "Tripoli"],
  South_Aegean: ["Rhodes", "Mykonos", "Santorini"],
  Thessaly: ["Larissa", "Trikala", "Kalambaka"],
  West_Greece: ["Patras", "Agrinio", "Amaliada"],
  West_Macedonia: ["Kozani", "Kastoria", "Grevena"],
  Budapest: ["Budapest"],
  Baranya: ["Pécs", "Szigetvár"],
  Békés: ["Békéscsaba", "Gyula"],
  "Borsod-Abaúj-Zemplén": ["Miskolc", "Kazincbarcika"],
  Csongrád: ["Szeged", "Hódmezővásárhely"],
  Fejér: ["Székesfehérvár", "Dunaújváros"],
  "Győr-Moson-Sopron": ["Győr", "Sopron"],
  "Hajdú-Bihar": ["Debrecen", "Hajdúszoboszló"],
  Heves: ["Eger", "Gyöngyös"],
  "Jász-Nagykun-Szolnok": ["Szolnok", "Jászberény"],
  "Komárom-Esztergom": ["Esztergom", "Tatabánya"],
  Nógrád: ["Balassagyarmat", "Pásztó"],
  Pest: ["Váci", "Kisvárda"],
  Somogy: ["Kapósvár", "Kaposvár"],
  "Szabolcs-Szatmár-Bereg": ["Nyíregyháza", "Szatmárnémeti"],
  Tolna: ["Szekszárd", "Bonyhád"],
  Vas: ["Szombathely", "Kőszeg"],
  Veszprém: ["Veszprém", "Balatonfüred"],
  Zala: ["Zalaegerszeg", "Lenti"],
  Capital_Region: ["Reykjavik", "Kopavogur", "Hafnarfjordur"],
  Southern: ["Selfoss", "Hvolsvollur", "Vik"],
  WesternIceland: ["Akranes", "Borgarnes", "Snæfellsbær"],
  Westfjords: ["Isafjordur", "Patreksfjordur", "Bolungarvik"],
  Northeast: ["Akureyri", "Húsavík", "Fjallabyggð"],
  Northwest: ["Stykkisholmur", "Búðardalur", "Dalasýsla"],
  East: ["Egilsstaðir", "Reydarfjordur", "Fjardabyggd"],
  South: ["Selfoss", "Hvolsvollur", "Vik"],
  Dublin: ["Dublin"],
  Cork: ["Cork", "Mallow"],
  Galway: ["Galway", "Tuam"],
  Limerick: ["Limerick"],
  Waterford: ["Waterford"],
  Clare: ["Ennis", "Shannon"],
  Kerry: ["Tralee", "Killarney"],
  Kildare: ["Naas", "Newbridge"],
  Kilkenny: ["Kilkenny"],
  Laois: ["Portlaoise"],
  Leitrim: ["Carrick-on-Shannon"],
  Louth: ["Drogheda", "Dundalk"],
  Mayo: ["Castlebar", "Ballina"],
  Meath: ["Navan"],
  Offaly: ["Tullamore"],
  Roscommon: ["Roscommon"],
  Sligo: ["Sligo"],
  Tipperary: ["Clonmel", "Tipperary"],
  Westmeath: ["Athlone"],
  Wexford: ["Wexford"],
  Wicklow: ["Wicklow"],
  Abruzzo: ["L'Aquila", "Pescara"],
  Aosta_Valley: ["Aosta"],
  Apulia: ["Bari", "Lecce"],
  Basilicata: ["Potenza", "Matera"],
  Calabria: ["Catanzaro", "Reggio Calabria"],
  Campania: ["Naples", "Salerno"],
  "Emilia-Romagna": ["Bologna", "Modena"],
  Friuli_Venezia_Giulia: ["Trieste", "Udine"],
  Lazio: ["Rome", "Frosinone"],
  Liguria: ["Genoa", "La Spezia"],
  Lombardy: ["Milan", "Bergamo"],
  Marche: ["Ancona", "Pesaro"],
  Molise: ["Campobasso", "Isernia"],
  Piedmont: ["Turin", "Novara"],
  Sardinia: ["Cagliari", "Sassari"],
  Sicily: ["Palermo", "Catania"],
  Tuscany: ["Florence", "Pisa"],
  Umbria: ["Perugia", "Terni"],
  Veneto: ["Venice", "Verona"],
  "Trentino-Alto_Adige": ["Trento", "Bolzano"],
  Chișinău: ["Chișinău"],
  Bălți: ["Bălți"],
  Tiraspol: ["Tiraspol"],
  Briceni: ["Briceni"],
  Cahul: ["Cahul"],
  Căușeni: ["Căușeni"],
  Edineț: ["Edineț"],
  Fălești: ["Fălești"],
  Orhei: ["Orhei"],
  Soroca: ["Soroca"],
  Sîngerei: ["Sîngerei"],
  Strășeni: ["Strășeni"],
  Ungheni: ["Ungheni"],
  Monaco: ["Monaco"],
  Podgorica: ["Podgorica"],
  Nikšić: ["Nikšić"],
  "Herceg Novi": ["Herceg Novi"],
  Bijelo_Polje: ["Bijelo Polje"],
  Pljevlja: ["Pljevlja"],
  Tivat: ["Tivat"],
  Budva: ["Budva"],
  Bar: ["Bar"],
  Kotor: ["Kotor"],
  Ulcinj: ["Ulcinj"],
  Rožaje: ["Rožaje"],
  Berane: ["Berane"],
  Amsterdam: ["Amsterdam"],
  Rotterdam: ["Rotterdam"],
  The_Hague: ["The Hague"],
  Utrecht: ["Utrecht"],
  Eindhoven: ["Eindhoven"],
  Tilburg: ["Tilburg"],
  Groningen: ["Groningen"],
  Almere: ["Almere"],
  Breda: ["Breda"],
  Nijmegen: ["Nijmegen"],
  Haarlem: ["Haarlem"],
  Arnhem: ["Arnhem"],
  Amersfoort: ["Amersfoort"],
  Zaanstad: ["Zaanstad"],
  Apeldoorn: ["Apeldoorn"],
  "'s-Hertogenbosch": ["'s-Hertogenbosch"],
  Skopje: ["Skopje"],
  Bitola: ["Bitola"],
  Kumanovo: ["Kumanovo"],
  Tetovo: ["Tetovo"],
  Ohrid: ["Ohrid"],
  Veles: ["Veles"],
  Prilep: ["Prilep"],
  Strumica: ["Strumica"],
  Shtip: ["Shtip"],
  Kavadarci: ["Kavadarci"],
  Gevgelija: ["Gevgelija"],
  Oslo: ["Oslo"],
  Bergen: ["Bergen"],
  Stavanger: ["Stavanger"],
  Tromsø: ["Tromsø"],
  Trondheim: ["Trondheim"],
  Drammen: ["Drammen"],
  Bærum: ["Bærum"],
  Sandnes: ["Sandnes"],
  Fredrikstad: ["Fredrikstad"],
  Porsgrunn: ["Porsgrunn"],
  Ålesund: ["Ålesund"],
  Haugesund: ["Haugesund"],
  Warsaw: ["Warsaw"],
  Kraków: ["Kraków"],
  Łódź: ["Łódź"],
  Wrocław: ["Wrocław"],
  Poznań: ["Poznań"],
  Gdańsk: ["Gdańsk"],
  Szczecin: ["Szczecin"],
  Bydgoszcz: ["Bydgoszcz"],
  Lublin: ["Lublin"],
  Katowice: ["Katowice"],
  Białystok: ["Białystok"],
  Gdynia: ["Gdynia"],
  Częstochowa: ["Częstochowa"],
  Lisbon: ["Lisbon"],
  Porto: ["Porto"],
  Braga: ["Braga"],
  Coimbra: ["Coimbra"],
  Aveiro: ["Aveiro"],
  Faro: ["Faro"],
  Setúbal: ["Setúbal"],
  Évora: ["Évora"],
  Viseu: ["Viseu"],
  Leiria: ["Leiria"],
  Alba: ["Alba Iulia", "Blaj", "Cîmpeni", "Sebeș", "Teiuș", "Aiud", "Bistra", "Cergău", "Ciugud", "Mărășești", 
    "Săliștea", "Sâncrai", "Sântimbru", "Țălnar", "Vințu de Jos"],
  Arad: ["Arad", "Ineu", "Pâncota", "Nădlac", "Sântana", 
     "Bătuța", "Bocsig", "Bălțați", "Căpâlnaș", "Curtici", 
     "Macea", "Miniș", "Pecica", "Păuliș", "Săvârșin"],
  Bacău: ["Bacău", "Moinești", "Buhuși", "Comănești", "Slănic Moldova", 
      "Adjud", "Bălășești", "Bârlălești", "Crasna", "Dărmănești", 
      "Mărășești", "Răcăciuni", "Săucești", "Sărata", "Ștefan cel Mare"],
  Bihor: ["Oradea", "Salonta", "Marghita", "Aleșd", "Nusfalău", 
     "Beiuș", "Borod", "Buntești", "Căbești", "Cheresig", 
     "Dobrești", "Hidișel", "Lazuri de Beiuș", "Sălard", "Tinca"],
  Bistrița_Năsăud: ["Bistrița", "Bistrița Bârgăului", "Năsăud", "Sângeorz-Băi", 
               "Braniștea", "Ciceu Giurgești", "Ciceu Mihăiești", "Ilva Mică", 
               "Matei", "Telciu", "Tiha Bârgăului", "Zagra"],
  Brașov: ["Brașov", "Făgăraș", "Rupea", "Zărnești", "Predeal", 
       "Hălchiu", "Hărman", "Sânpetru", "Tărlungeni", 
       "Ghimbav", "Moieciu de Sus", "Râșnov"],
  Brăila: ["Brăila", "Însurăței", "Făurei", "Chiscani", 
       "Buchilaș", "Cazasu", "Ciocile", "Dărdășeni", 
       "Grădiștea", "Măcin", "Mărașu", "Șuțești"],
  Buzău: ["Buzău", "Râmnicu Sărat", "Nehoiu", "Pogoanele", 
      "Brădeanu", "Cernătești", "Cilibia", "Cozia", 
      "Mărăcineni", "Săhăteni", "Scurta", "Vadu Pașii"],
  Caraș_Severin: ["Reșița", "Caransebeș", "Bocșa", "Moldova Nouă", 
              "Anina", "Băile Herculane", "Bocșa Română", "Ciclova Română", 
              "Glimboca", "Oravița", "Oțelu Roșu"],
  Călărași: ["Călărași", "Borcea", "Oltenița", "Fundulea", 
         "Bălăceanu", "Călărași Sud", "Chiciu", "Făurei", 
         "Florești", "Valea Argovei"],
  Cluj: ["Cluj-Napoca", "Gherla", "Turda", "Câmpia Turzii", 
     "Huedin", "Dej", "Așchileu", "Băișoara", 
     "Beliș", "Chinteni", "Feleacu", "Florești", 
     "Iara", "Mărișel", "Săvădisla"],
  Constanța: ["Constanța", "Mangalia", "Năvodari", "Eforie Nord", 
          "Ovidiu", "Medgidia", "Cernavodă", "Agigea", 
          "Baneasa", "Cumpăna", "Eforie Sud", "Hârșova", 
          "Murfatlar", "Năvodari", "Târgușor"],
  Covasna: ["Sfântu Gheorghe", "Târgu Secuiesc", "Baraolt", 
        "Bățani", "Cernat", "Dârjiu", "Întorsura Buzăului", 
        "Ozun", "Zăbala"],
  Dâmbovița: ["Târgoviște", "Moreni", "Fieni", 
          "Aninoasa", "Băleni", "Buciumeni", "Făcăeni", 
          "Pucioasa", "Titu"],
  Dolj: ["Craiova", "Filiași", "Băilești", "Dăbuleni", 
     "Segarcea", "Calafat", "Cetate", "Ișalnița", 
     "Malu Mare", "Poiana Mare", "Predești", "Râpa de Jos", "Șimnic"],
  Galați: ["Galați", "Tecuci", "Târgu Bujor", "Liești", "Bălăurești", 
       "Brăila", "Cosmești", "Ghidigeni", "Ijdileni", 
       "Oancea", "Smârdan", "Șendreni"],
  Giurgiu: ["Giurgiu", "Bolintin-Vale", "Mihăilești", "Adunați-Copăceni", 
        "Comana", "Găujani", "Grădinari", "Gura Bătrânei", 
        "Hotarele", "Izvoarele", "Pârlogu"],
  Gorj: ["Târgu Jiu", "Motru", "Rovinari", "Bălănești", 
     "Albeni", "Baia de Fier", "Bălești", "Dănciulești", 
     "Rânca", "Săcelu", "Tismana"],
  Harghita: ["Miercurea Ciuc", "Odorheiu Secuiesc", "Toplița", 
         "Băile Tușnad", "Borsec", "Ciumani", 
         "Joseni", "Sânmartin"],
  Hunedoara: ["Deva", "Hunedoara", "Orăștie", "Simeria", 
         "Brad", "Călan", "Certeju de Sus", "Nădlac", 
         "Sălașu de Sus", "Teliucu Inferior"],
  Ialomița: ["Slobozia", "Fetești", "Urziceni", "Căzănești", 
         "Bărbulești", "Ciochina", "Coșereni", "Grivița", 
         "Mărculești", "Rădulești"],
  Iași: ["Iași", "Pașcani", "Hârlău", "Târgu Frumos", 
     "Botoșani", "Cajvana", "Cotnari", "Deleni", 
     "Tomești", "Valea Lupului"],
  Maramureș: ["Baia Mare", "Sighetu Marmației", "Târgu Lăpuș", 
         "Șomcuta Mare", "Borșa", "Oarța de Jos", 
         "Rona de Jos", "Copalnic Mănăștur", "Vadu Izei"],
  Mehedinți: ["Drobeta-Turnu Severin", "Orșova", "Baia de Aramă", 
         "Șimian", "Goruia", "Livezile", "Poroina Mare", 
         "Bălăcița"],
  Mureș: ["Târgu Mureș", "Reghin", "Sighișoara", "Luduș", 
     "Iernut", "Sâncraiu de Mureș", "Târgu Mureș", 
     "Gălășeni", "Hodoșa"],
  Neamț: ["Piatra Neamț", "Roman", "Târgu Neamț", "Bicaz", 
     "Roznov", "Săvinești", "Păstrăveni", "Bâra", 
     "Bălțătești"],
  Olt: ["Slatina", "Caracal", "Coroiești", "Drăgănești-Olt", 
    "Piatra-Olt", "Potcoava", "Scornicești"],
  Prahova: ["Ploiești", "Câmpina", "Vălenii de Munte", "Breaza", 
       "Băicoi", "Azuga", "Bălcești", "Măgurele"],
  Satu_Mare: ["Satu Mare", "Carei", "Tășnad", "Livada", 
          "Baia Mare", "Păulești", "Sanislău"],
  Sibiu: ["Sibiu", "Mediaș", "Avrig", "Miercurea Sibiului", 
      "Tălmaciu", "Ocna Sibiului", "Agnita", "Cisnădieș"],
  Suceava: ["Suceava", "Câmpulung Moldovenesc", "Rădăuți", 
        "Fălticeni", "Siret", "Gura Humorului", 
        "Dolhasca", "Botoșana"],
  Teleorman: ["Alexandria", "Roșiorii de Vede", "Zimnicea", 
          "Turnu Măgurele", "Videle", "Băcau", "Băleni"],
  Timiș: ["Timișoara", "Recaș", "Sânnicolau Mare", "Jimbolia", 
      "Făget", "Buziaș", "Deta", "Gătaia", "Ciacova"],
  Tulcea: ["Tulcea", "Măcin", "Săceni", "Babadag", "Isaccea", 
       "Nufăru", "Murighiol", "Sulina"],
  Vaslui: ["Vaslui", "Bârlad", "Negrești", "Huși", "Murgeni", 
       "Albești", "Dănești", "Mălăiești"],
  Vrancea: ["Focșani", "Adjud", "Mărășești", "Panciu", "Vidra", 
        "Dălhăuți", "Jariștea", "Vulturu"],
  București: ["București", "Bucureștii Noi", "Berceni", "Bragadiru", 
         "Chiajna", "Otopeni", "Voluntari"],
};
